title: GitHook Giphy

description: "Add gifs to your PRs through the power of Giphy."

thumbnail: http://giphy.com/static/img/giphy_logo_square_social.png

entry_point: gif.js

triggered_on:
  - pull_request

scopes_required:
  - 'repo'
